services:
  iotplatform-api:
    image: ${DOCKER_REGISTRY-}iotplatform-api
    container_name: IotPlatform.Api
    build:
      context: .
      dockerfile: IotPlatform.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"

  iotplatform-reporting-api:
    image: ${DOCKER_REGISTRY-}iotplatform-reporting-api
    container_name: IotPlatform.Reporting.Api
    build:
      context: .
      dockerfile: IotPlatform.Reporting.Api/Dockerfile
    ports:
      - "6000:8080"
      - "6001:8081"

  iotplatform-presentation:
    image: iotplatform-ui:latest
    container_name: IotPlatform.Presentation
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3000:80"
      
  iotplatform-db:
    image: postgres:latest
    container_name: IotPlatform.Db
    environment:
      - POSTGRES_DB=iotplatform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  iotplatform-mq:
    image: rabbitmq:management
    container_name: IotPlatform.RabbitMq
    hostname: iotplatform-mq
    volumes:
      - ./.containers/queue/data/:/var/lib/rabbitmq
      - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
