# 这是一个生成的文件。不用于手动编辑。
services:
  contentplatform-api:
    build:
      context: "C:\\Users\\cheng\\github\\aspire-orchestration\\ContentPlatform"
      dockerfile: "ContentPlatform.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/ContentPlatform.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "contentplatform-api:dev"
    ports: []
    volumes:
    - "C:\\Users\\cheng\\github\\aspire-orchestration\\ContentPlatform\\ContentPlatform.Api:/app:rw"
    - "C:\\Users\\cheng\\github\\aspire-orchestration\\ContentPlatform:/src:rw"
    - "C:\\Users\\cheng\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  contentplatform-reporting-api:
    build:
      context: "C:\\Users\\cheng\\github\\aspire-orchestration\\ContentPlatform"
      dockerfile: "ContentPlatform.Reporting.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/ContentPlatform.Reporting.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "contentplatform-reporting-api:dev"
    ports: []
    volumes:
    - "C:\\Users\\cheng\\github\\aspire-orchestration\\ContentPlatform\\ContentPlatform.Reporting.Api:/app:rw"
    - "C:\\Users\\cheng\\github\\aspire-orchestration\\ContentPlatform:/src:rw"
    - "C:\\Users\\cheng\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
